### ISSUE TITLE
Google Play Services 11.0.0 doesn't work with GooglePlayCallbackExtractor.java

### ISSUE THREAD

**Issue by highel** [firebase/firebase-jobdispatcher-android#117]
GooglePlayCallbackExtractor.java does not work with the latest Google Play Services 11.0.0

line `return new GooglePlayJobCallback(((PendingCallback) parcelledCallback).getIBinder());`
references `PendingCallback.getIBinder()` method which was removed in 11.0.0

**Comment by unEgor** [comment]
Thank you for filing the issue. We are working on it right now.
The fix will be ready soon.

**Comment by androideveloper** [comment]
Any updates?

**Comment by colintheshots** [comment]
I can't upgrade Google Play Services until this is resolved and there are useful Location updates in the newest version.

**Comment by zhihuitang** [comment]
doesn't work with play services 11.0
```
6-21 22:52:03.885 17295-17295/com.halebop.servicetips.test E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.halebop.servicetips.test, PID: 17295
  java.lang.NoSuchMethodError: No virtual method getIBinder()Landroid/os/IBinder; in class Lcom/google/android/gms/gcm/PendingCallback; or its super classes (declaration of 'com.google.android.gms.gcm.PendingCallback' appears in /data/app/com.halebop.servicetips.test-1/split_lib_dependencies_apk.apk:classes25.dex)
      at com.firebase.jobdispatcher.GooglePlayCallbackExtractor.extractCallback(GooglePlayCallbackExtractor.java:48)
      at com.firebase.jobdispatcher.GooglePlayReceiver.prepareJob(GooglePlayReceiver.java:159)
      at com.firebase.jobdispatcher.GooglePlayReceiver.onStartCommand(GooglePlayReceiver.java:98)
      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
      at android.app.ActivityThread.-wrap17(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5417)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by samy-baili** [comment]
Same problem

**Comment by unEgor** [comment]
Sorry for the inconvenience. We are working on it right now.

**Comment by diegomontoya** [comment]
11.0.1 is also broken. Please up the priority of this. I am surprised firebase-dispatcher was NOT tested before v11 of the play service was release.

**Comment by lpellegr** [comment]
@unEgor any update?

**Comment by unEgor** [comment]
Please review https://github.com/firebase/firebase-jobdispatcher-android/pull/123
I plan to test one more time and submit it tomorrow.
Sorry for the delay.

**Comment by ciarand** [comment]
This should be fixed with the v0.7.0 release

**Comment by OtreborShm** [comment]
@unEgor any updates for this issue? version 11.0.2 still broken

**Comment by FabianTerhorst** [comment]
It works.

**Comment by vit001** [comment]
Still broken in 11.4.0

**Comment by sarathch** [comment]
@vit001 This is fixed in v0.7.0 +. Make sure you compile firebase jobdispatcher.

**Comment by vit001** [comment]
@sarathch - Got it, thanks.
